"""
Test script for TransformerDistAngleConfEstimator model trained by
train_transformer_dist_angle_conf.py.

Loads a trained checkpoint and evaluates on the test datasets generated by
csi_generator_test.py.  The test datasets use **different** distances, angles,
and random seed — guaranteeing zero overlap with training data.

Reports:
  - Overall MAE / RMSE for distance, angle, confidence
  - Per-obstruction-level breakdown
  - Inference time per sample
  - Comprehensive visualizations saved to transformer_figures/
"""

import torch
import numpy as np
import matplotlib.pyplot as plt
from torch.utils.data import TensorDataset, DataLoader
from collections import defaultdict
import json
import time
import os

# Reuse model class and preprocessing from the training script
from train_transformer_dist_angle_conf import (
    TransformerDistAngleConfEstimator,
    pre_processing_dist_angle_conf,
)


# ============================================================
# Helpers
# ============================================================
def count_model_params(model: torch.nn.Module) -> dict:
    """Count parameters and estimate model size (float32)."""
    total = sum(p.numel() for p in model.parameters())
    trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    size_mb = total * 4 / (1024 * 1024)                     # float32 → 4 bytes
    return {'total_params': total, 'trainable_params': trainable, 'size_mb': size_mb}


def load_checkpoint(checkpoint_path: str, device: torch.device):
    """Load trained TransformerDistAngleConfEstimator + scalers from a .pth checkpoint."""
    print(f"Loading checkpoint: {checkpoint_path}")
    checkpoint = torch.load(checkpoint_path, map_location="cpu", weights_only=False)

    cfg = checkpoint['model_config']
    num_subcarriers = cfg['num_subcarriers']
    num_rx          = cfg['num_rx']
    scaler_dist     = checkpoint['scaler_dist']
    scaler_sincos   = checkpoint['scaler_sincos']
    scaler_y        = checkpoint['scaler_y']

    best_str = ""
    if 'best_val_loss' in checkpoint:
        best_str = f" (best val_loss: {checkpoint['best_val_loss']:.4f})"
    print(f"  Trained for {checkpoint.get('epoch', '?')} epochs{best_str}")

    model = TransformerDistAngleConfEstimator(
        num_subcarriers=num_subcarriers,
        num_rx=num_rx,
        d_model=cfg.get('d_model', 64),
        nhead=cfg.get('nhead', 4),
        num_layers=cfg.get('num_layers', 4),
        dim_feedforward=cfg.get('dim_feedforward', 256),
        dropout=cfg.get('dropout', 0.1),
        hidden_dims_head=cfg.get('hidden_dims_head', (128, 64)),
    )

    model.load_state_dict(checkpoint['model_state_dict'])
    model.eval()
    model = model.to(device)

    info = count_model_params(model)
    print(f"  Model: {info['total_params']:,} params  ({info['size_mb']:.2f} MB)")
    print(f"  d_model={cfg['d_model']}, nhead={cfg['nhead']}, "
          f"layers={cfg['num_layers']}, "
          f"token_dim_per_sc={model.d_per_sc}")

    # Also compute n_phase / n_sincos for preprocessing compatibility
    n_phase  = 2 * num_subcarriers
    n_sincos = 2 * (num_rx - 1) * num_subcarriers

    return model, n_phase, n_sincos, scaler_dist, scaler_sincos, scaler_y


# ============================================================
# Chunked Inference (avoids OOM for large test sets)
# ============================================================
@torch.no_grad()
def predict_chunked(processed_csi, model, n_phase, n_sincos,
                    scaler_dist, scaler_sincos, scaler_y, device):
    """
    Run inference on large feature array in chunks.

    Args:
        processed_csi: ndarray or memmap, shape [N, n_phase + n_sincos]
        model, scalers, device: from load_checkpoint

    Returns:
        predictions:  ndarray [N, 3] in original physical units (d, a, c)
        avg_inference_us: average model forward time per sample (µs)
    """
    n_total = processed_csi.shape[0]
    chunk_size = min(5000, n_total)
    batch_size = 64
    all_preds = []
    total_model_time = 0.0

    for start in range(0, n_total, chunk_size):
        end = min(start + chunk_size, n_total)
        chunk = processed_csi[start:end]

        # ── Apply saved normalization ──
        if scaler_dist is not None:
            X_phase = scaler_dist.transform(chunk[:, :n_phase]).astype(np.float32)
        else:
            X_phase = chunk[:, :n_phase].astype(np.float32)

        if scaler_sincos is not None:
            X_sincos = scaler_sincos.transform(chunk[:, n_phase:]).astype(np.float32)
        else:
            X_sincos = chunk[:, n_phase:].astype(np.float32)

        X_chunk = np.concatenate([X_phase, X_sincos], axis=1)
        del X_phase, X_sincos

        dataset = TensorDataset(torch.from_numpy(X_chunk))
        loader  = DataLoader(dataset, batch_size=batch_size)
        del X_chunk

        for (xb,) in loader:
            xb = xb.to(device).float()

            t0 = time.perf_counter()
            pred = model(xb)                              # [batch, 3]  — flat input
            total_model_time += time.perf_counter() - t0

            all_preds.append(pred.cpu().numpy())

    preds_norm = np.concatenate(all_preds)              # [N, 3]

    # Inverse-transform distance & angle (cols 0, 1); confidence (col 2)
    # is already in [0,1] via sigmoid — no inverse needed.
    if scaler_y is not None:
        predictions = np.zeros_like(preds_norm)
        predictions[:, :2] = scaler_y.inverse_transform(preds_norm[:, :2])
        predictions[:, 2]  = preds_norm[:, 2]
    else:
        predictions = preds_norm

    avg_inference_us = total_model_time / n_total * 1e6
    return predictions, avg_inference_us


# ============================================================
# Metrics
# ============================================================
def compute_metrics(predictions, labels):
    """
    Args:
        predictions: [N, 3]  (dist, angle, conf)
        labels:      [N, 3]  (dist, angle, conf)

    Returns:
        dict with mae/rmse for dist, angle, conf
    """
    err_dist  = predictions[:, 0] - labels[:, 0]
    err_angle = predictions[:, 1] - labels[:, 1]
    err_conf  = predictions[:, 2] - labels[:, 2]

    return {
        'mae_dist':   float(np.mean(np.abs(err_dist))),
        'rmse_dist':  float(np.sqrt(np.mean(err_dist ** 2))),
        'mae_angle':  float(np.mean(np.abs(err_angle))),
        'rmse_angle': float(np.sqrt(np.mean(err_angle ** 2))),
        'mae_conf':   float(np.mean(np.abs(err_conf))),
        'rmse_conf':  float(np.sqrt(np.mean(err_conf ** 2))),
    }


def print_metrics(label, m, prefix=""):
    print(f"  {prefix}{label}:")
    print(f"    Distance   — MAE: {m['mae_dist']:.4f} m,  RMSE: {m['rmse_dist']:.4f} m")
    print(f"    Angle      — MAE: {m['mae_angle']:.2f}°,   RMSE: {m['rmse_angle']:.2f}°")
    print(f"    Confidence — MAE: {m['mae_conf']:.4f},   RMSE: {m['rmse_conf']:.4f}")


# ============================================================
# Visualization  (IEEE journal style — scienceplots + manual rcParams)
# ============================================================
def _ieee_style():
    """Apply IEEE journal plotting style."""
    try:
        plt.style.use(['science', 'ieee'])
    except Exception:
        pass  # scienceplots not installed — fall back to manual rcParams
    plt.rcParams.update({
        'font.family':      'serif',
        'font.serif':       ['Times New Roman'],
        'font.size':        7,
        'axes.labelsize':   7,
        'axes.titlesize':   7,
        'xtick.labelsize':  7,
        'ytick.labelsize':  7,
        'legend.fontsize':  7,
        'lines.linewidth':  1.2,
        'figure.dpi':       300,
        'text.usetex':      False,
        'savefig.bbox':     'tight',
    })


def visualize_results(predictions, labels, per_level_metrics, meta, bw):
    """
    Generate publication-quality IEEE-style test-set plots.

    Produces 4 separate figures:
      Fig 1 — Distance & Angle:  predicted vs true (color by confidence)
      Fig 2 — Confidence analysis: histogram + pred vs true scatter
      Fig 3 — Per-obstruction-level MAE curves
      Fig 4 — Error distributions + distance error vs confidence
    """
    _ieee_style()

    preds_dist   = predictions[:, 0]
    preds_angle  = predictions[:, 1]
    preds_conf   = predictions[:, 2]
    labels_dist  = labels[:, 0]
    labels_angle = labels[:, 1]
    labels_conf  = labels[:, 2]

    err_dist  = preds_dist - labels_dist
    err_angle = preds_angle - labels_angle
    err_conf  = preds_conf - labels_conf
    err_dist_abs = np.abs(err_dist)

    los_mask  = labels_conf > 0.5
    nlos_mask = ~los_mask
    pred_conf_los  = preds_conf[los_mask]  if los_mask.sum()  > 0 else np.array([])
    pred_conf_nlos = preds_conf[nlos_mask] if nlos_mask.sum() > 0 else np.array([])

    # ── Per-label averages ──
    unique_distances = sorted(set(labels_dist))
    unique_angles    = sorted(set(labels_angle))

    dist_label_to_preds = defaultdict(list)
    angle_label_to_preds = defaultdict(list)
    for pd_, pa_, td, ta in zip(preds_dist, preds_angle, labels_dist, labels_angle):
        dist_label_to_preds[int(td)].append(float(pd_))
        angle_label_to_preds[int(ta)].append(float(pa_))

    dist_avg  = np.array([np.mean(dist_label_to_preds[int(d)]) for d in unique_distances])
    angle_avg = np.array([np.mean(angle_label_to_preds[int(a)]) for a in unique_angles])

    # ── Per-level MAE curves ──
    conf_vals_sorted   = sorted(per_level_metrics.keys())
    mae_dist_by_level  = [per_level_metrics[c]['mae_dist']  for c in conf_vals_sorted]
    mae_angle_by_level = [per_level_metrics[c]['mae_angle'] for c in conf_vals_sorted]
    mae_conf_by_level  = [per_level_metrics[c]['mae_conf']  for c in conf_vals_sorted]
    wall_loss_dB = [round((1.0 - c) * 100) for c in conf_vals_sorted]

    m = compute_metrics(predictions, labels)
    out_dir = "transformer_figures"
    os.makedirs(out_dir, exist_ok=True)

    # ================================================================
    #  Fig 1 — Distance & Angle: Predicted vs True  (2×1, ~7 in wide)
    # ================================================================
    fig1, (ax1a, ax1b) = plt.subplots(1, 2, figsize=(7, 3.2))

    # (a) Distance
    sc = ax1a.scatter(labels_dist, preds_dist,
                      c=preds_conf, cmap='RdYlGn', alpha=0.25, s=3,
                      vmin=0, vmax=1)
    ax1a.plot(unique_distances, dist_avg, 'k-', alpha=0.8, linewidth=1.2)
    d_min, d_max = min(unique_distances), max(unique_distances)
    ax1a.plot([d_min, d_max], [d_min, d_max], 'r--', linewidth=1.0)
    ax1a.set_xlabel("True Distance (m)")
    ax1a.set_ylabel("Predicted Distance (m)")
    ax1a.set_title(f"(a)  Distance  (MAE = {m['mae_dist']:.3f} m)")
    ax1a.grid(True, alpha=0.3)

    # (b) Angle
    sc2 = ax1b.scatter(labels_angle, preds_angle,
                       c=preds_conf, cmap='RdYlGn', alpha=0.25, s=3,
                       vmin=0, vmax=1)
    ax1b.plot(unique_angles, angle_avg, 'k-', alpha=0.8, linewidth=1.2)
    a_min, a_max = min(unique_angles), max(unique_angles)
    ax1b.plot([a_min, a_max], [a_min, a_max], 'r--', linewidth=1.0)
    ax1b.set_xlabel("True Angle (deg)")
    ax1b.set_ylabel("Predicted Angle (deg)")
    ax1b.set_title(f"(b)  Angle  (MAE = {m['mae_angle']:.1f}°)")
    ax1b.grid(True, alpha=0.3)

    cbar = fig1.colorbar(sc, ax=[ax1a, ax1b],
                         label="Predicted Confidence", shrink=0.92, pad=0.02)
    cbar.ax.tick_params(labelsize=6)
    cbar.set_label("Predicted Confidence", fontsize=7)

    fig1.tight_layout()
    fig1.savefig(f"{out_dir}/csi_test_dist_angle_pred_{bw}MHz.svg")
    fig1.savefig(f"{out_dir}/csi_test_dist_angle_pred_{bw}MHz.png")
    plt.close(fig1)

    # ================================================================
    #  Fig 2 — Confidence Analysis  (2×1)
    # ================================================================
    fig2, (ax2a, ax2b) = plt.subplots(1, 2, figsize=(7, 3.2))

    # (a) Confidence histogram  (LOS green, NLOS red)
    ax2a.hist(pred_conf_los,  bins=25, alpha=0.6, edgecolor='black', linewidth=0.3,
              color='#2ca02c', label=f'True LOS  (n={len(pred_conf_los)})')
    ax2a.hist(pred_conf_nlos, bins=25, alpha=0.5, edgecolor='black', linewidth=0.3,
              color='#d62728', label=f'True NLOS (n={len(pred_conf_nlos)})')
    ax2a.set_xlabel("Predicted Confidence")
    ax2a.set_ylabel("Count")
    ax2a.set_title(f"(a)  Confidence Distribution  (MAE = {m['mae_conf']:.4f})")
    ax2a.legend(loc='upper center', framealpha=0.9)
    ax2a.grid(True, alpha=0.3)

    # (b) Confidence: Predicted vs True  (per-level means marked)
    ax2b.scatter(labels_conf, preds_conf, alpha=0.25, s=3, color='#1f77b4')
    ax2b.plot([0, 1], [0, 1], 'r--', linewidth=1.0)
    ax2b.set_xlabel("True Confidence")
    ax2b.set_ylabel("Predicted Confidence")
    ax2b.set_title(f"(b)  Confidence: Predicted vs True")
    ax2b.grid(True, alpha=0.3)
    for cv in conf_vals_sorted:
        mask = np.isclose(labels_conf, cv, atol=0.05)
        if mask.sum() > 0:
            ax2b.plot(cv, np.mean(preds_conf[mask]), 'ko', markersize=3, alpha=0.8)

    fig2.tight_layout()
    fig2.savefig(f"{out_dir}/csi_test_confidence_{bw}MHz.svg")
    fig2.savefig(f"{out_dir}/csi_test_confidence_{bw}MHz.png")
    plt.close(fig2)

    # ================================================================
    #  Fig 3 — Per-Obstruction-Level MAE  (3×1)
    # ================================================================
    fig3, (ax3a, ax3b, ax3c) = plt.subplots(1, 3, figsize=(7, 2.7))

    ax3a.plot(wall_loss_dB, mae_dist_by_level, 'o-', linewidth=1.2,
              color='#1f77b4', markersize=4)
    ax3a.set_xlabel("Wall Loss (dB)")
    ax3a.set_ylabel("Distance MAE (m)")
    ax3a.set_title("(a)  Distance MAE")
    ax3a.grid(True, alpha=0.3)
    ax3a.invert_xaxis()

    ax3b.plot(wall_loss_dB, mae_angle_by_level, 's-', linewidth=1.2,
              color='#ff7f0e', markersize=4)
    ax3b.set_xlabel("Wall Loss (dB)")
    ax3b.set_ylabel("Angle MAE (deg)")
    ax3b.set_title("(b)  Angle MAE")
    ax3b.grid(True, alpha=0.3)
    ax3b.invert_xaxis()

    ax3c.plot(wall_loss_dB, mae_conf_by_level, '^-', linewidth=1.2,
              color='#2ca02c', markersize=4)
    ax3c.set_xlabel("Wall Loss (dB)")
    ax3c.set_ylabel("Confidence MAE")
    ax3c.set_title("(c)  Confidence MAE")
    ax3c.grid(True, alpha=0.3)
    ax3c.invert_xaxis()

    fig3.tight_layout()
    fig3.savefig(f"{out_dir}/csi_test_mae_vs_wall_loss_{bw}MHz.svg")
    fig3.savefig(f"{out_dir}/csi_test_mae_vs_wall_loss_{bw}MHz.png")
    plt.close(fig3)

    # ================================================================
    #  Fig 4 — Error Distributions  (2×2)
    # ================================================================
    fig4, ((ax4a, ax4b), (ax4c, ax4d)) = plt.subplots(2, 2, figsize=(7, 5.5))

    # (a) Distance error histogram
    ax4a.hist(err_dist, bins=50, edgecolor='black', linewidth=0.3,
              alpha=0.7, color='#1f77b4')
    ax4a.axvline(0, color='r', linestyle='--', linewidth=0.8)
    ax4a.set_xlabel("Distance Error (m)")
    ax4a.set_ylabel("Count")
    ax4a.set_title(f"(a)  Distance Error  (std = {np.std(err_dist):.3f} m)")
    ax4a.grid(True, alpha=0.3)

    # (b) Angle error histogram
    ax4b.hist(err_angle, bins=50, edgecolor='black', linewidth=0.3,
              alpha=0.7, color='#ff7f0e')
    ax4b.axvline(0, color='r', linestyle='--', linewidth=0.8)
    ax4b.set_xlabel("Angle Error (deg)")
    ax4b.set_ylabel("Count")
    ax4b.set_title(f"(b)  Angle Error  (std = {np.std(err_angle):.1f}°)")
    ax4b.grid(True, alpha=0.3)

    # (c) Confidence error histogram
    ax4c.hist(err_conf, bins=50, edgecolor='black', linewidth=0.3,
              alpha=0.7, color='#2ca02c')
    ax4c.axvline(0, color='r', linestyle='--', linewidth=0.8)
    ax4c.set_xlabel("Confidence Error")
    ax4c.set_ylabel("Count")
    ax4c.set_title(f"(c)  Confidence Error  (std = {np.std(err_conf):.4f})")
    ax4c.grid(True, alpha=0.3)

    # (d) Distance error vs predicted confidence
    ax4d.scatter(preds_conf, err_dist_abs, alpha=0.15, s=3, color='#9467bd')
    if len(err_dist_abs) > 1:
        coeff = np.polyfit(preds_conf, err_dist_abs, 1)
        x_fit = np.linspace(0, 1, 100)
        ax4d.plot(x_fit, np.polyval(coeff, x_fit), 'r-', linewidth=1.2,
                  label=f'Slope: {coeff[0]:.3f}')
        ax4d.legend(fontsize=6, loc='upper right')
    ax4d.set_xlabel("Predicted Confidence")
    ax4d.set_ylabel("Absolute Distance Error (m)")
    ax4d.set_title("(d)  Distance Error vs Confidence")
    ax4d.grid(True, alpha=0.3)

    fig4.tight_layout()
    fig4.savefig(f"{out_dir}/csi_test_errors_{bw}MHz.svg")
    fig4.savefig(f"{out_dir}/csi_test_errors_{bw}MHz.png")
    plt.close(fig4)

    print(f"  Figures saved to {out_dir}/ (4 figures × .svg + .png)")


# ============================================================
# Main Test Routine
# ============================================================
def test_dist_angle_conf(bw: int, checkpoint_path: str):
    """
    Load the test datasets for a given bandwidth, run inference, report results.

    Args:
        bw:               bandwidth (MHz) — used to construct file paths
        checkpoint_path:  path to trained .pth checkpoint
    """
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    # ── Load model & scalers ──
    model, n_phase, n_sincos, scaler_dist, scaler_sincos, scaler_y = \
        load_checkpoint(checkpoint_path, device)

    # ── Test dataset parameters (must match csi_generator_test.py) ──
    NUM_LEVELS = 10
    conf_labels = [round(1.0 - lvl * 0.1, 1) for lvl in range(NUM_LEVELS)]
    #  [1.0, 0.9, 0.8, ..., 0.1]

    all_preds_arr = []
    all_labels_arr = []
    per_level_metrics = {}
    total_preprocess_time = 0.0
    total_inference_time = 0.0
    total_samples = 0

    for lvl in range(NUM_LEVELS):
        conf_val = conf_labels[lvl]
        wall_dB  = lvl * 10

        path_data = f"CSI_Test_Angle_Dataset_{bw}MHz_4Rx_conf_{conf_val}.npz"
        path_meta = f"metadata_CSI_Test_Angle_Dataset_{bw}MHz_4Rx_conf_{conf_val}.json"

        print(f"\n[{lvl+1}/{NUM_LEVELS}] Level {lvl}: "
              f"wall_loss={wall_dB} dB, confidence={conf_val}")

        if not os.path.exists(path_data):
            print(f"  SKIP: {path_data} not found. "
                  f"Run csi_generator_test.py first.")
            continue

        # ── Preprocess ──
        t0 = time.time()
        phase_data, label_array, meta = pre_processing_dist_angle_conf(
            path_to_data=path_data,
            path_to_meta=path_meta,
            confidence_label=conf_val,
        )
        total_preprocess_time += time.time() - t0

        # ── Inference ──
        predictions, avg_inf_us = predict_chunked(
            phase_data, model, n_phase, n_sincos,
            scaler_dist, scaler_sincos, scaler_y, device,
        )

        n_level = len(predictions)
        total_samples += n_level
        total_inference_time += avg_inf_us * n_level / 1e6  # convert µs → s

        all_preds_arr.append(predictions)
        all_labels_arr.append(label_array)

        # ── Per-level metrics ──
        m = compute_metrics(predictions, label_array)
        per_level_metrics[conf_val] = m

        print_metrics(f"Level {lvl} (conf={conf_val})", m, prefix="  ")

        # Free memory
        del phase_data, predictions, label_array

    # ── Combine all levels ──
    all_preds  = np.concatenate(all_preds_arr, axis=0)
    all_labels = np.concatenate(all_labels_arr, axis=0)

    overall_m = compute_metrics(all_preds, all_labels)

    print(f"\n{'='*70}")
    print(f"TEST SET OVERALL RESULTS — {bw} MHz")
    print(f"{'='*70}")
    print(f"  Total samples:  {total_samples:,}")
    print(f"  Preprocess:     {total_preprocess_time:.1f} s")
    print(f"  Inference:      {total_inference_time:.1f} s "
          f"({total_inference_time / total_samples * 1e6:.1f} us/sample)")
    print_metrics("OVERALL", overall_m)

    # ── LOS vs NLOS breakdown ──
    los_mask  = all_labels[:, 2] > 0.5
    nlos_mask = ~los_mask
    if los_mask.sum() > 0 and nlos_mask.sum() > 0:
        print(f"\n{'─'*70}")
        print("Breakdown by scenario:")
        los_m  = compute_metrics(all_preds[los_mask],  all_labels[los_mask])
        nlos_m = compute_metrics(all_preds[nlos_mask], all_labels[nlos_mask])
        print_metrics("LOS  (no wall)", los_m)
        print_metrics("NLOS (wall)",    nlos_m)

    # ── Per-level summary table ──
    print(f"\n{'─'*70}")
    print(f"{'Level':<6} {'Wall(dB)':<10} {'Conf':<6} "
          f"{'Dist MAE':<12} {'Angle MAE':<12} {'Conf MAE':<12}")
    print(f"{'─'*70}")
    for conf_val in sorted(per_level_metrics.keys(), reverse=True):
        m = per_level_metrics[conf_val]
        wall_dB = int(round((1.0 - conf_val) * 100))
        print(f"{int((1.0 - conf_val) * 10):<6} "
              f"{wall_dB:<10} "
              f"{conf_val:<6} "
              f"{m['mae_dist']:<12.4f} "
              f"{m['mae_angle']:<12.2f} "
              f"{m['mae_conf']:<12.4f}")

    # ── Visualize ──
    visualize_results(all_preds, all_labels, per_level_metrics, meta, bw)

    return overall_m, per_level_metrics, all_preds, all_labels


# ============================================================
# Entry Point
# ============================================================
if __name__ == "__main__":
    # Test on the same bandwidth(s) used for training
    bw_list = [20]            # add 40, 80, 100 as needed

    for bw in bw_list:
        print(f"\n{'#'*70}")
        print(f"#  TESTING — Bandwidth = {bw} MHz  —  TransformerDistAngleConfEstimator")
        print(f"{'#'*70}")

        path_checkpoint = f"transformer_checkpoint_dist_angle_conf_{bw}MHz.pth"

        if not os.path.exists(path_checkpoint):
            print(f"  Checkpoint not found: {path_checkpoint}")
            print(f"  Run train_transformer_dist_angle_conf.py first.")
            continue

        test_dist_angle_conf(bw, path_checkpoint)
